### ISSUE TITLE
Create a basic PCB

### ISSUE THREAD

**Issue by ccachin** [fablabs-ch/wordclock#16]
A polyvalent PCB seems to be not so attractive and people are a bit lost when they have to find where to solder the components.
Idea is to have a smaller pcb with the only mandatory components.

Can maybe linked with issue #7 Try to use an ESP8266 as brain

**Comment by gaetancollaud** [comment]
I tried PlatformIO recently. It's amazing how the ESP8266 is easy with this platform. Of course we have a lot of refactoring to do... :(

**Comment by ccachin** [comment]
What kind of refactoring should we do to use PlateformIO?

**Comment by gaetancollaud** [comment]
Since I used C++ 90% of the code is compatible. The issue will be the led strip and the i2c communication. We have to use other libraries.

**Comment by ccachin** [comment]
Basic pcb created. See wordclock_zero
