### ISSUE TITLE
Create a PCB to hold the rotary button

### ISSUE THREAD

**Issue by gaetancollaud** [fablabs-ch/wordclock#8]

**Comment by ccachin** [comment]
PCB already exists. 
https://www.aliexpress.com/item/Free-shipping-KEYES-Rotary-encoder-module-for-arduino-with-demo-code/2050939127.html?spm=2114.01010208.3.21.pgrOsD&ws_ab_test=searchweb0_0,searchweb201602_2_10065_10068_10000007_10084_10083_10080_10082_10081_10060_10061_10062_10056_10055_10037_10054_10033_10059_10032_10099_10078_10079_10077_10073_10097_10100_10096_10070_10052_10050_424_10051,searchweb201603_6&btsid=64e2a3b7-18a0-4f39-956c-f1c14e2e7ab4

The pcb has to have 5 pins header male to plug a flat cable. 
Has to be reviewed on main pcb only.

**Comment by ccachin** [comment]
Finally decided to reject this issue. Pull-up are worst on rotary encoder module.
